apiVersion: v1
kind: Service
metadata:
  name: calculadora-go-minikube
  labels:
    app: calculadora-go-minikube
    role: master
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: calculadora-go-minikube
    role: master
    tier: backend