# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-script
   date > /etc/vagrant_provisioned_at \
   && ./calculadora
   
script

Vagrant.configure(2) do |config|
   config.vm.box = "hashicorp/precise64"
   config.vm.network "private_network", ip: "77.77.77.7"
   config.vm.provision "file", source: "Vagrantfile", destination: "$HOME"
   config.vm.provision "file", source: "calculadora", destination: "calculadora"
   config.vm.provision "shell", inline: $script
end